name: ecom
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.1+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1
  shared_preferences: ^0.5.12
  image: ^2.1.18
  image_picker: ^0.6.7+11
  provider: ^4.3.2+2
  path_provider: ^1.6.18
  flutter_staggered_grid_view: ^0.3.2
  fluttertoast: ^7.1.1
  intl:
  flutter_spinkit: ^4.1.2+1
  material_design_icons_flutter: ^4.0.5655
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
